stages:
  - lint

Lint:
  stage: lint
  tags:
    - bfs
  script: 
    - cpplint --verbose=0 src/excitation.h
    - cpplint --verbose=0 src/chirp.h
    - cpplint --verbose=0 src/doublet.h
    - cpplint --verbose=0 src/multisine.h
    - cpplint --verbose=0 src/pulse.h
    - cpplint --verbose=0 src/sampled.h
    - cpplint --verbose=0 src/chirp.cpp
    - cpplint --verbose=0 src/doublet.cpp
    - cpplint --verbose=0 src/multisine.cpp
    - cpplint --verbose=0 src/pulse.cpp
    - cpplint --verbose=0 src/sampled.cpp
